export enum Commands {
  CREATE_USER = 'CREATE_USER',
  GET_QUESTIONS_BY_USER = 'GET_QUESTIONS_BY_USER',
  GET_EXAMS_BY_USER = 'GET_EXAMS_BY_USER',
  GET_CONSUMER_AVAILABLE_EXAMS_HEADER = 'GET_CONSUMER_AVAILABLE_EXAMS_HEADER',
  GET_CONSUMER_AVAILABLE_EXAM = 'GET_CONSUMER_AVAILABLE_EXAM',
  GET_EXAM_ANSWERS = 'GET_EXAM_ANSWERS',
  GET_ALL_USER_EXAM_ANSWERS_BY_OWNER = 'GET_ALL_USER_EXAM_ANSWERS_BY_OWNER',
  LOGIN = 'LOGIN',
  AUTHORIZE = 'AUTHORIZE'
}
