export enum ProvidersEvents {
  CREATE_QUESTION = 'CREATE_QUESTION',
  CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS',
  CREATE_EXAM = 'CREATE_EXAM',
  CREATE_EXAM_SUCCESS = 'CREATE_EXAM_SUCCESS',
}
